.SILENT:

AR_x86=/usr/bin/ar
AWK=/usr/bin/awk
CAT=/usr/bin/cat
CC_x86=/usr/bin/gcc
CD=cd
CONFIG_CFLAGS=-W -Wall -g -m32
CONFIG_LDFLAGS=--warn-common
CONFIG_QEMU_x86= -fda grub-boot-only.img 
COPY=/usr/bin/cp
CP=/usr/bin/cp
CXX_x86=/usr/bin/g++
ECHO=/usr/bin/echo
ELF_MODE=elf_i386
GREP=/usr/bin/grep
GZIP=/usr/bin/gzip
INSTRUMENTATION=0
KILL=/usr/bin/kill
LD_x86=/usr/bin/ld
MKDIR=/usr/bin/mkdir
MV=/usr/bin/mv
OBJCOPY_x86=/usr/bin/objcopy
OBJDUMP_x86=/usr/bin/objdump
PERL=/usr/bin/perl
QEMU_x86=/usr/bin/qemu-system-i386
RANLIB_x86=/usr/bin/ranlib
RM=/usr/bin/rm -r -f
SED=/usr/bin/sed
SLEEP=/usr/bin/sleep
TOUCH=/usr/bin/touch
